config/routes.rb
Rails.application.routes.draw do
  # refactor routes -- paths are too long

  scope '(:locale)' do
    resources :websites do
      resources :blogs, only: [:new, :create, :destroy] do
        resources :posts do
          resources :widgets
          member do
            get :toggle_status
          end
        end
      end
      resources :pages do
        resources :images, only: [:create, :edit, :update, :destroy]
        resources :widgets, only: [:sort, :create, :edit, :update, :destroy] do
          put :sort, on: :collection, as: :sort
        end
      end
      resources :navbars do
        resources :links, only: [:create, :destroy]
      end
    end
    get 'about', to: 'static_pages#about'
    root to: 'static_pages#home'
    get 'static_pages/home'

    get 'static_pages/about'

    devise_for :users

    mount ActionCable.server => '/cable'
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :website
  has_many :posts
end

app/models/color_combo.rb
class ColorCombo < ApplicationRecord
  has_many :websites
end

app/models/image.rb
class Image < Widget
end

app/models/layout.rb
class Layout < ApplicationRecord
  has_many :pages

  mount_uploader :image, ImageUploader
  mount_uploader :document, StylesUploader
  mount_uploader :sheet, StylesUploader
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :navbar
  belongs_to :page
end

app/models/nav_style.rb
class NavStyle < ApplicationRecord
  has_many :navbars
end

app/models/navbar.rb
class Navbar < ApplicationRecord
  belongs_to :website
  belongs_to :nav_style
  has_many :links
  has_many :pages, through: :links
  enum position: { main: 0, footer: 1 }

  def add_link(page)
    links.build(page_id: page.id)
    save
  end
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :website
  belongs_to :layout, optional: true
  has_many :links
  has_many :navbars, through: :links
  has_many :widgets, as: :widgetable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :blog
  enum status: { draft: 0, published: 1 }

  def toggle_status
    if draft?
      published!
    else
      draft!
    end
  end
end

app/models/text.rb
class Text < Widget
end

app/models/user.rb
class User < ApplicationRecord
  has_many :websites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :user
  has_many :pages
  has_many :navbars
  belongs_to :color_combo, optional: true
  has_one :blog

  def footer
    navbars.where(position: 'footer').first
  end

  def main_nav
    navbars.where(position: 'main').first
  end
end

app/models/widget.rb
class Widget < ApplicationRecord
  belongs_to :widgetable, polymorphic: true
  mount_uploader :image, ImageUploader

  def self.by_position
    order('position ASC')
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/navbars_helper.rb
module NavbarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
  def stylesheet(website)
    if website.color_combo.present?
      website.color_combo.name.downcase
    else
      'application'
    end
  end

  def has_blog?(website)
    !website.blog.nil?
  end

  def page_link_exists?(navbar, page)
    !navbar.pages.where(id: page.id).empty?
  end

  def current_link(navbar, page)
    link = Link.where(page_id: page.id, navbar_id: navbar.id).first
  end

  def website_footer?(website)
    !website.navbars.where(position: 'footer').empty?
  end

  def website_main_nav?(website)
    !website.navbars.where(position: 'main').empty?
  end

  def navbar_style(navbar)
    return navbar.nav_style.name if navbar.nav_style.present?
  end

  def main_nav(website)
    nav_items = website.navbars.where(position: 'main').first.pages
    nav_links = ''
    nav_items.each do |item|
      item_url = website_page_path(website, item, locale: I18n.locale)
      nav_links << "<li><a href='#{item_url}' class='nav-link #{active? item_url}' >#{item.title}</a></li>"
    end
    nav_links.html_safe
  end

  def footer_nav(website)
    footer_items = website.footer.pages
    footer_links = ''
    if footer_items.empty?
      footer_links << 'Add Pages to the Footer'
    else
      footer_items.each do |item|
        item_url = website_page_path(website, item, locale: I18n.locale)
        footer_links << "<li><a href='#{item_url}' class='nav-link #{active? item_url}' >#{item.title}</a></li>"
      end
    end
    footer_links.html_safe
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  def content(widget)
    if widget.type == 'Image'
      image_tag(widget.content, width: '100%')
    else
      widget.content
    end
  end
end

app/views/shared/_empty_website_footer.html.erb
<div class="mastfoot app-footer" id="emptyfooter">
  <div class="inner">
    <h4>No Footer navigation has been added - <li><%= link_to t('websites.show.add_footer'), new_website_navbar_path(@website, locale:I18n.locale)%></li> </h4>
  </div>
</div>

app/views/shared/_empty_website_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-danger blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button"
    data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to "Logo goes here", root_path, class:"navbar-brand h3"%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li><%= link_to t('websites.show.add_nav'), new_website_navbar_path(@website, locale:I18n.locale), class:"nav-link"%></li> 
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_nav.html.erb
<!-- Figure out where to put the toggle button
Functionality works -->


<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse blog-nav fixed-top" id="cmsNav">
  <button class="navbar-toggler navbar-toggler-right" type="button"
    data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to "RailsCMS", root_path, class:"navbar-brand h3"%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper "nav-link", "li"%>
        <li><input type=button value="Toggle View" onclick="showHideDiv('#sidebar');" class="btn btn-small btn-primary nav-link"></li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t('languages') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to locale: "en" do %>
              <%= content_tag :span, "English", :class => "dropdown-item" %>
            <% end %>
            <%= link_to locale: "pt" do %>
              <%= content_tag :span, "Português", :class => "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav pull-right">
        <%= login_helper "nav-link "%>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_website_footer.html.erb
<div class="mastfoot app-footer" id="footer">
  <div class="inner">
    <%= footer_nav(@website) %>
    <li><%= link_to t('websites.show.edit_nav'), edit_website_navbar_path(@website, @website.footer, locale:I18n.locale), class:"nav-link"%></li>
  </div>
</div>

app/views/shared/_website_nav.html.erb
<% if navbar_style(@website.main_nav) == 'style1' %>

  <nav class="navbar navbar-toggleable-md navbar-inverse bg-danger blog-nav nav-style1" id="main_nav">
    <button class="navbar-toggler navbar-toggler-right" type="button"
      data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
      <%= link_to "Logo goes here", root_path, class:"navbar-brand h3"%>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <%= main_nav(@website) %>
          <li><%= link_to t('websites.show.edit_nav'), edit_website_navbar_path(@website, @website.navbars.first, locale:I18n.locale), class:"nav-link"%></li>
        </ul>
      </div>
    </div>
  </nav>
<% else %>
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-danger blog-nav nav-style2" id="main_nav">
    <button class="navbar-toggler navbar-toggler-right" type="button"
      data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
      <%= link_to "Logo goes here", root_path, class:"navbar-brand h3"%>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <%= main_nav(@website) %>
          <li><%= link_to t('websites.show.edit_nav'), edit_website_navbar_path(@website, @website.navbars.first, locale:I18n.locale), class:"nav-link"%></li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>  

app/views/shared/_website_sidebar.html.erb
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <%= link_to 'Overview', website_path(@website, locale: I18n.locale), class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Navbars', website_navbars_path(@website, locale: I18n.locale), class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Pages', website_pages_path(@website, locale: I18n.locale), class:"nav-link"%>
    </li>
    <li class="nav-item">
      <% if has_blog?(@website) %>
        <%= link_to 'Blog', website_blogs_path(@website, locale: I18n.locale), class:"nav-link"%>
      <% else %>
        <%= link_to 'Blog', new_website_blog_path(@website, locale: I18n.locale), class:"nav-link"%>
      <% end %>
    </li>
  
  </ul>


  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <%= link_to 'My Profile', edit_user_registration_path(locale: I18n.locale), class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'My Other Sites', websites_path(locale: I18n.locale), class:"nav-link"%>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Another nav item</a>
    </li>
  </ul>