config/routes.rb
Rails.application.routes.draw do
  # refactor routes -- paths are too long

  scope '(:locale)' do
    resources :websites do
      resources :blogs, only: [:new, :create, :destroy] do
        resources :posts do
          resources :widgets
          member do
            get :toggle_status
          end
        end
      end
      resources :pages do
        resources :images, only: [:create, :edit, :update, :destroy]
        resources :widgets, only: [:sort, :create, :edit, :update, :destroy] do
          put :sort, on: :collection, as: :sort
        end
      end
      resources :navbars do
        resources :links, only: [:create, :destroy]
      end
    end
    get 'about', to: 'static_pages#about'
    root to: 'static_pages#home'
    get 'static_pages/home'

    get 'static_pages/about'

    devise_for :users

    mount ActionCable.server => '/cable'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :website
  has_many :posts
end

app/models/color_combo.rb
class ColorCombo < ApplicationRecord
  has_many :websites
end

app/models/image.rb
class Image < Widget
end

app/models/layout.rb
class Layout < ApplicationRecord
  has_many :pages

  mount_uploader :image, ImageUploader
  mount_uploader :document, StylesUploader
  mount_uploader :sheet, StylesUploader
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :navbar
  belongs_to :page
end

app/models/nav_style.rb
class NavStyle < ApplicationRecord
  has_many :navbars
end

app/models/navbar.rb
class Navbar < ApplicationRecord
  belongs_to :website
  belongs_to :nav_style
  has_many :links
  has_many :pages, through: :links
  enum position: { main: 0, footer: 1 }

  def add_link(page)
    links.build(page_id: page.id)
    save
  end
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :website
  belongs_to :layout, optional: true
  has_many :links
  has_many :navbars, through: :links
  has_many :widgets, as: :widgetable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :blog
  enum status: { draft: 0, published: 1 }

  def toggle_status
    if draft?
      published!
    else
      draft!
    end
  end
end

app/models/text.rb
class Text < Widget
end

app/models/user.rb
class User < ApplicationRecord
  has_many :websites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :user
  has_many :pages
  has_many :navbars
  belongs_to :color_combo, optional: true
  has_one :blog

  def footer
    navbars.where(position: 'footer').first
  end

  def main_nav
    navbars.where(position: 'main').first
  end
end

app/models/widget.rb
class Widget < ApplicationRecord
  belongs_to :widgetable, polymorphic: true
  mount_uploader :image, ImageUploader

  def self.by_position
    order('position ASC')
  end
end

app/controllers/navbars_controller.rb
class NavbarsController < ApplicationController
  before_action :set_website
  before_action :set_navbar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  layout 'website'
  # GET /navbars
  def index
    @navbars = Navbar.all
  end

  # GET /navbars/1
  def show; end

  # GET /navbars/new
  def new
    @navbar = Navbar.new
  end

  # GET /navbars/1/edit
  def edit; end

  # POST /navbars
  def create
    @navbar = @website.navbars.build(navbar_params)
    if @navbar.save
      redirect_to website_navbars_path(@website, locale: I18n.locale), notice: t('.navbar_succes')
    else
      render :new
    end
  end

  # PATCH/PUT /navbars/1
  def update
    if @navbar.update(navbar_params)
      redirect_to website_navbars_path(@website, locale: I18n.locale), notice: t('.navbar_updated')
    else
      render :edit
    end
  end

  # DELETE /navbars/1
  def destroy
    @navbar.destroy
    redirect_to website_navbars_url(@website, locale: I18n.locale), notice: t('.navbar_destroyed')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_navbar
    @navbar = Navbar.find(params[:id])
  end

  def set_website
    @website = Website.find(params[:website_id])
  end

  # Only allow a trusted parameter "white list" through.
  def navbar_params
    params.require(:navbar).permit(:title, :nav_style_id, :website_id, :position)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper(style = '')
    if user_signed_in?
      link_to t('logout'), destroy_user_session_path(locale: I18n.locale), method: :delete, class: style
    else
      (link_to t('login'), new_user_session_path(locale: I18n.locale), class: style) + ' '.html_safe +
        (link_to t('register'), new_user_registration_path(locale: I18n.locale), class: style)
    end
  end

  def nav_items
    [
      {
        url: root_path(params[:locale]),
        title: t('.home')
      },

      {
        url: about_path(params[:locale]),
        title: t('.about')
      },
      {
        url: websites_path(params[:locale]),
        title: t('.my_websites')
      }

    ]
  end

  def nav_helper(style, tag_type)
    nav_links = ''
    nav_items.each do |item|
      nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}' >#{item[:title]}</a></#{tag_type}>"
    end
    nav_links.html_safe
  end

  def active?(path)
    'active' if current_page? path
  end

  def alerts
    alert = (flash[:alert] || flash[:error] || flash[:notice])
    alert_generator alert if alert
  end

  def alert_generator(msg)
    js add_gritter(msg, title: 'Fix my name on the alert generator method in your application_helper', sticky: false)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/navbars_helper.rb
module NavbarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
  def stylesheet(website)
    if website.color_combo.present?
      website.color_combo.name.downcase
    else
      'application'
    end
  end

  def has_blog?(website)
    !website.blog.nil?
  end

  def page_link_exists?(navbar, page)
    !navbar.pages.where(id: page.id).empty?
  end

  def current_link(navbar, page)
    link = Link.where(page_id: page.id, navbar_id: navbar.id).first
  end

  def website_footer?(website)
    !website.navbars.where(position: 'footer').empty?
  end

  def website_main_nav?(website)
    !website.navbars.where(position: 'main').empty?
  end

  def navbar_style(navbar)
    return navbar.nav_style.name if navbar.nav_style.present?
  end

  def main_nav(website)
    nav_items = website.navbars.where(position: 'main').first.pages
    nav_links = ''
    nav_items.each do |item|
      item_url = website_page_path(website, item, locale: I18n.locale)
      nav_links << "<li><a href='#{item_url}' class='nav-link #{active? item_url}' >#{item.title}</a></li>"
    end
    nav_links.html_safe
  end

  def footer_nav(website)
    footer_items = website.footer.pages
    footer_links = ''
    if footer_items.empty?
      footer_links << 'Add Pages to the Footer'
    else
      footer_items.each do |item|
        item_url = website_page_path(website, item, locale: I18n.locale)
        footer_links << "<li><a href='#{item_url}' class='nav-link #{active? item_url}' >#{item.title}</a></li>"
      end
    end
    footer_links.html_safe
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  def content(widget)
    if widget.type == 'Image'
      image_tag(widget.content, width: '100%')
    else
      widget.content
    end
  end
end

app/views/navbars/_form.html.erb
<% if @navbar.errors.any? %>
  <% @navbar.errors.full_messages.each do |error| %>
    <li><%= alert_generator error %></li>
  <% end %>
<% end %>
<div class="from-group">
  <%= f.label :title %>
  <%= f.text_field :title, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :nav_style_id, t(".style") %>
  <%= f.collection_radio_buttons(:nav_style_id, NavStyle.all, :id, :name, {class:"form-control"})  %>
</div>
<div class="form-group">
  <%= f.radio_button :position, :main %>
  <%= f.label :position, t(".main")%>

  <%= f.radio_button :position, :footer %>
  <%= f.label :position, t(".footer")%>
</div>

app/views/navbars/_navbar.html.erb
<!--- TO DO
Add the correct style for the navbar -->

<nav class="navbar navbar-toggleable-md navbar-inverse bg-danger blog-nav nav-style1" id="main_nav">
  <button class="navbar-toggler navbar-toggler-right" type="button"
    data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to "Logo goes here", root_path, class:"navbar-brand h3"%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-link"><%= navbar.position%> - <%= navbar.title %></li>
        <%= main_nav(@website) %>
        <li><%= link_to t('websites.show.edit_nav'), edit_website_navbar_path(@website, navbar, locale:I18n.locale), class:"nav-link"%></li>
        <li> <%= link_to t('delete'), website_navbar_path(@website, navbar, locale: I18n.locale), method: :delete, data: { confirm: t('are_you_sure') }, class:"nav-link" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/navbars/edit.html.erb
<h1><%= t('editing') %>  Navbar</h1>
<%= form_for(@navbar, url:website_navbar_path(@website, @navbar, locale: I18n.locale) ) do |f| %>

  <%= render 'form', f:f %>

  <div class="form-group">
    <%= f.submit t('.update'), class:"btn btn-primary" %>
  </div>
  <% end %>

<%= link_to fa_icon('folder-open-o'), website_navbar_path(@website,@navbar, locale:I18n.locale) %> |
<%= link_to fa_icon('arrow-circle-left'), website_navbars_path(@website, locale:I18n.locale) %>

app/views/navbars/index.html.erb
<h2><%= t('.Navbars') %></h2>


  <%= render @navbars %>

<br>

<%= link_to fa_icon('plus 2x'), new_website_navbar_path(@website, locale:I18n.locale) %>

<% if @website.pages.empty? %>
  <%= link_to 'Add pages first', new_website_page_path(@website, locale:I18n.locale) %>
<% else %>
  <h3>Choose the pages to add to your navbar</h3>

  <table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Page Title</th>
      <th>Main Nav</th>
      <th>Footer</th>
    </tr>
  </thead>
  <tbody>
    <% @website.pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td>
          <% if website_main_nav?(@website) %>
            <% if page_link_exists?(@website.main_nav, page) %>
              <%= link_to 'Remove from Main Nav',
                website_navbar_link_path(
                      @website,
                      @website.main_nav,
                      current_link(@website.main_nav, page),
                      locale: I18n.locale,
                      page_id: page.id),
                method: :delete,
                id:"remove_from_main_#{page.id}"%>
            <% else %>
              <%= link_to 'Add to Main Nav',
                website_navbar_links_path(
                      @website,
                      @website.main_nav,
                      locale: I18n.locale,
                      page_id: page.id),
                method: :post,
                id:"add_to_main_#{page.id}"%>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if website_footer?(@website) %>
            <% if page_link_exists?(@website.footer, page) %>
              <%= link_to 'Remove from Footer',
                website_navbar_link_path(
                      @website,
                      @website.footer,
                      current_link(@website.footer, page),
                      locale: I18n.locale,
                      page_id: page.id),
                method: :delete,
                id:"add_to_footer_#{page.id}"%>
            <% else %>
              <%= link_to 'Add to Footer',
                website_navbar_links_path(
                      @website,
                      @website.footer,
                      locale: I18n.locale,
                      page_id: page.id),
                method: :post,
                id:"remove_from_footer_#{page.id}"%>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/navbars/new.html.erb
<h1><%= t('adding') %> Navbar</h1>

<%= form_for([@website,@navbar], url:website_navbars_path(locale: I18n.locale) ) do |f| %>

  <%= render 'form',  f: f %>

  <div class="form-group">
    <%= f.submit t('.create'), class:'btn btn-primary' %>
  </div>
  <% end %>


<%= link_to fa_icon('arrow-circle-left'), website_navbars_path(@website, locale:I18n.locale) %>

app/views/navbars/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @navbar.title %>
</p>

<p>
  <strong>Style:</strong>
  <%= @navbar.style %>
</p>



<%= link_to fa_icon('edit 2x'), edit_website_navbar_path(@website,@navbar, locale:I18n.locale) %> |
<%= link_to fa_icon('arrow-circle-left 2x'), website_navbars_path(@website, locale:I18n.locale) %>