config/routes.rb
Rails.application.routes.draw do
  # refactor routes -- paths are too long

  scope '(:locale)' do
    resources :websites do
      resources :blogs, only: [:new, :create, :destroy] do
        resources :posts do
          resources :widgets
          member do
            get :toggle_status
          end
        end
      end
      resources :pages do
        resources :images, only: [:create, :edit, :update, :destroy]
        resources :widgets, only: [:sort, :create, :edit, :update, :destroy] do
          put :sort, on: :collection, as: :sort
        end
      end
      resources :navbars do
        resources :links, only: [:create, :destroy]
      end
    end
    get 'about', to: 'static_pages#about'
    root to: 'static_pages#home'
    get 'static_pages/home'

    get 'static_pages/about'

    devise_for :users

    mount ActionCable.server => '/cable'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :website
  has_many :posts
end

app/models/color_combo.rb
class ColorCombo < ApplicationRecord
  has_many :websites
end

app/models/image.rb
class Image < Widget
end

app/models/layout.rb
class Layout < ApplicationRecord
  has_many :pages

  mount_uploader :image, ImageUploader
  mount_uploader :document, StylesUploader
  mount_uploader :sheet, StylesUploader
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :navbar
  belongs_to :page
end

app/models/nav_style.rb
class NavStyle < ApplicationRecord
  has_many :navbars
end

app/models/navbar.rb
class Navbar < ApplicationRecord
  belongs_to :website
  belongs_to :nav_style
  has_many :links
  has_many :pages, through: :links
  enum position: { main: 0, footer: 1 }

  def add_link(page)
    links.build(page_id: page.id)
    save
  end
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :website
  belongs_to :layout, optional: true
  has_many :links
  has_many :navbars, through: :links
  has_many :widgets, as: :widgetable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :blog
  enum status: { draft: 0, published: 1 }

  def toggle_status
    if draft?
      published!
    else
      draft!
    end
  end
end

app/models/text.rb
class Text < Widget
end

app/models/user.rb
class User < ApplicationRecord
  has_many :websites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :user
  has_many :pages
  has_many :navbars
  belongs_to :color_combo, optional: true
  has_one :blog

  def footer
    navbars.where(position: 'footer').first
  end

  def main_nav
    navbars.where(position: 'main').first
  end
end

app/models/widget.rb
class Widget < ApplicationRecord
  belongs_to :widgetable, polymorphic: true
  mount_uploader :image, ImageUploader

  def self.by_position
    order('position ASC')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_website
  before_action :set_blog
  before_action :check_website_owner, only: [:new, :create, :edit, :update, :destroy, :toggle_status]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :toggle_status]
  # GET /posts
  def index
    @posts = @blog.posts
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = @blog.posts.build(post_params)
    if @post.save
      redirect_to website_blog_post_path(@website, @blog, @post, locale: I18n.locale), notice: t('.post_succes')
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to website_blog_post_path(@website, @blog, @post, locale: I18n.locale), notice: t('.post_updated')
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to website_blog_posts_path(@website, @blog, locale: I18n.locale), notice: t('.post_destroyed')
  end

  def toggle_status
    @post.toggle_status
    redirect_to website_blog_posts_path(@website, @blog, locale: I18n.locale), notice: t('.success')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_website
    @website = Website.find(params[:website_id])
  end

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end

  def check_website_owner
    @website = Website.find(params[:website_id])
    redirect_to root_path unless current_user == @website.user
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:title, :content, :status, :blog_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper(style = '')
    if user_signed_in?
      link_to t('logout'), destroy_user_session_path(locale: I18n.locale), method: :delete, class: style
    else
      (link_to t('login'), new_user_session_path(locale: I18n.locale), class: style) + ' '.html_safe +
        (link_to t('register'), new_user_registration_path(locale: I18n.locale), class: style)
    end
  end

  def nav_items
    [
      {
        url: root_path(params[:locale]),
        title: t('.home')
      },

      {
        url: about_path(params[:locale]),
        title: t('.about')
      },
      {
        url: websites_path(params[:locale]),
        title: t('.my_websites')
      }

    ]
  end

  def nav_helper(style, tag_type)
    nav_links = ''
    nav_items.each do |item|
      nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}' >#{item[:title]}</a></#{tag_type}>"
    end
    nav_links.html_safe
  end

  def active?(path)
    'active' if current_page? path
  end

  def alerts
    alert = (flash[:alert] || flash[:error] || flash[:notice])
    alert_generator alert if alert
  end

  def alert_generator(msg)
    js add_gritter(msg, title: 'Fix my name on the alert generator method in your application_helper', sticky: false)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/navbars_helper.rb
module NavbarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
  def stylesheet(website)
    if website.color_combo.present?
      website.color_combo.name.downcase
    else
      'application'
    end
  end

  def has_blog?(website)
    !website.blog.nil?
  end

  def page_link_exists?(navbar, page)
    !navbar.pages.where(id: page.id).empty?
  end

  def current_link(navbar, page)
    link = Link.where(page_id: page.id, navbar_id: navbar.id).first
  end

  def website_footer?(website)
    !website.navbars.where(position: 'footer').empty?
  end

  def website_main_nav?(website)
    !website.navbars.where(position: 'main').empty?
  end

  def navbar_style(navbar)
    return navbar.nav_style.name if navbar.nav_style.present?
  end

  def main_nav(website)
    nav_items = website.navbars.where(position: 'main').first.pages
    nav_links = ''
    nav_items.each do |item|
      item_url = website_page_path(website, item, locale: I18n.locale)
      nav_links << "<li><a href='#{item_url}' class='nav-link #{active? item_url}' >#{item.title}</a></li>"
    end
    nav_links.html_safe
  end

  def footer_nav(website)
    footer_items = website.footer.pages
    footer_links = ''
    if footer_items.empty?
      footer_links << 'Add Pages to the Footer'
    else
      footer_items.each do |item|
        item_url = website_page_path(website, item, locale: I18n.locale)
        footer_links << "<li><a href='#{item_url}' class='nav-link #{active? item_url}' >#{item.title}</a></li>"
      end
    end
    footer_links.html_safe
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  def content(widget)
    if widget.type == 'Image'
      image_tag(widget.content, width: '100%')
    else
      widget.content
    end
  end
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |error| %>
    <li><%= alert_generator error %></li>
  <% end %>
<% end %>

            <div class="from-group">
        <%= f.label :title %>
        <%= f.text_field :title, class:"form-control" %>
      </div>
                  <div class="from-group">
        <%= f.label :content %>
        <%= f.text_area :content, class:"form-control" %>
      </div>
                  <div class="from-group">
        <%= f.label :status %>
        <%= f.number_field :status, class:"form-control" %>
      </div>
                  <div class="from-group">
        <%= f.label :blog_id %>
        <%= f.text_field :blog_id, class:"form-control" %>
      </div>
      

app/views/posts/edit.html.erb
<h1><%= t('editing') %>  Post</h1>
<%= form_for(@post, url:website_blog_post_path(@website, @blog, @post, locale: I18n.locale) ) do |f| %>

  <%= render 'form', f:f %>

  <div class="form-group">
    <%= f.submit t('.update'), class:"btn btn-primary" %>
  </div>
  <% end %>

<%= link_to fa_icon('folder-open-o'), website_blog_post_path(@website, @blog,@post, locale:I18n.locale) %> |
<%= link_to fa_icon('arrow-circle-left'), website_blog_posts_path(@website, @blog,locale:I18n.locale) %>

app/views/posts/index.html.erb
<% if @blog.posts.empty? %>
  <h2>Now you can start writing your blog</h2>
  <%= link_to 'Blog on Navbar?', '#', id: "blogToNavbar" %>
<% else %>
  <h2><%= t('.Posts') %></h2>

  <hr>

  <div>
    <% @posts.each do |post| %>
      <div class="content">
        <p><%= post.title %></p>
        <p><%= post.content %></p>
        <p><%= post.status %></p>
        <p><%= post.blog %></p>
        <p><%= link_to post.status, toggle_status_website_blog_post_path(@website, @blog, post, locale: I18n.locale), id:"toggle_status_#{post.id}" %></p>
        <p><%= link_to t('show'), website_blog_post_path(@website, @blog, post, locale: I18n.locale) %></p>
        <p><%= link_to t('edit'), edit_website_blog_post_path(@website, @blog,post,locale: I18n.locale) %></p>
        <p><%= link_to t('delete'), website_blog_post_path(@website, @blog,post, locale: I18n.locale), method: :delete, data: { confirm: t('are_you_sure') }, id:"delete_post_#{post.id}" %></p>
      </div>
    <% end %>
  </div>

  <br>
<% end %>

<%= link_to fa_icon('plus 2x'), new_website_blog_post_path(@website, @blog, locale:I18n.locale), id: "addPost" %>

app/views/posts/new.html.erb
<h1><%= t('adding') %> Post</h1>

<%= form_for([@website,@blog,@post], url:website_blog_posts_path( locale: I18n.locale) ) do |f| %>

  <%= render 'form',  f: f %>

  <div class="form-group">
    <%= f.submit t('.create'), class:'btn btn-primary' %>
  </div>
  <% end %>

<%= link_to fa_icon('arrow-circle-left 2x'), website_blog_posts_path(@website, @blog,locale:I18n.locale) %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @post.status %>
</p>


<%= link_to fa_icon('edit 2x'), edit_website_blog_post_path(@website, @blog,@post, locale: I18n.locale) %> |
<%= link_to fa_icon('arrow-circle-left 2x'), website_blog_posts_path(@website, @blog,locale: I18n.locale) %>